
env:
  global:
    - NODE_VERSION=stable

jobs:
  include:
  - language: android
    cache: yarn
    jdk: oraclejdk8
    dist: trusty
    sudo: required
    android:
      components:
        - build-tools-28.0.3
        - android-28
        - sys-img-x86-android-28
    install:
    - echo no | android create avd --force -n pixel9 -t android-28 --abi default/x86
    - curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    script:
    - yarn
    - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - npx detox build -c android.emu.release
    - npx detox test --headless -c android.emu.release --gpu swiftshader --cleanup
